{"timestamp": "2017-09-11T10:11:10.464225Z", "level": "CRITICAL", "message": "Unhandled exception: %s", "system": "Windows 10", "gh_handle": "Manfred28", "command": "C:\\Users\\pisti\\AppData\\Local\\Programs\\Python\\Python36-32\\Scripts\\gf verify hello_me.py", "feature": "VERIFY", "workshop_url": "https://github.com/greenfox-academy/teaching-materials/blob/master/workshop/expressions-and-control-flow/python.md", "language": "python", "exercise_name": "hello_me.py", "type": "<class 'UnicodeDecodeError'>", "value": "Exception: 'utf-8' codec can't decode byte 0xe1 in position 11: invalid continuation byte", "traceback": "File \"c:\\users\\pisti\\appdata\\local\\programs\\python\\python36-32\\lib\\runpy.py\", line 193, in _run_module_as_main\n    \"__main__\", mod_spec)\n  File \"c:\\users\\pisti\\appdata\\local\\programs\\python\\python36-32\\lib\\runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"C:\\Users\\pisti\\AppData\\Local\\Programs\\Python\\Python36-32\\Scripts\\gf.exe\\__main__.py\", line 9, in <module>\n    sys.exit(main())\n  File \"c:\\users\\pisti\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\gf\\app_starter.py\", line 15, in main\n    app_controller.run()\n  File \"c:\\users\\pisti\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\gf\\app_controller.py\", line 11, in run\n    task_check(get_command_argument())()\n  File \"c:\\users\\pisti\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\gf\\app_controller.py\", line 39, in verify_start\n    verify_service.start(get_link())\n  File \"c:\\users\\pisti\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\gf\\verify\\verify_service.py\", line 16, in start\n    verify(filename)\n  File \"c:\\users\\pisti\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\gf\\verify\\verify_service.py\", line 49, in verify\n    test_result = test_evaluate(commands)\n  File \"c:\\users\\pisti\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\gf\\verify\\result_process.py\", line 12, in test_evaluate\n    CommandType.RUN))\n  File \"c:\\users\\pisti\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\gf\\verify\\result_process.py\", line 22, in processing_result\n    result, run_command_list)\n  File \"c:\\users\\pisti\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\gf\\verify\\result_process.py\", line 51, in evaluate_regex_test\n    run_command_list[count].regex):\n  File \"c:\\users\\pisti\\appdata\\local\\programs\\python\\python36-32\\lib\\site-packages\\gf\\verify\\result_process.py\", line 32, in check_regex_match\n    output_list = output.decode(FILE_ENCODING).split(\"\\n\")"}
